"""Documented NES 2A03 instruction timing, not elapsed hardware scheduling.

Inputs describe ORIGINAL instruction bytes and PRE-instruction registers. The
indirect-Y base is a captured zero-page pointer, never an emulated bus read here.
DMA, DMC stalls and interrupt entry are separate events: this API cannot certify
an event-free interval. Unknown opcodes fail closed, including 65C816 COP bytes.
"""
from __future__ import annotations
from dataclasses import dataclass
from opcodes6502 import OPS

READ = {'imm': 2, 'zp': 3, 'zpx': 4, 'zpy': 4, 'abs': 4,
        'absx': 4, 'absy': 4, 'ix': 6, 'iy': 5}
SPECIAL = {'BRK': 7, 'JSR': 6, 'RTI': 6, 'RTS': 6,
           'PHP': 3, 'PHA': 3, 'PLP': 4, 'PLA': 4}
RMW = {'ASL', 'LSR', 'ROL', 'ROR', 'INC', 'DEC'}
BRANCHES = {'BPL': (0x80, False), 'BMI': (0x80, True),
            'BVC': (0x40, False), 'BVS': (0x40, True),
            'BCC': (0x01, False), 'BCS': (0x01, True),
            'BNE': (0x02, False), 'BEQ': (0x02, True)}


def metadata(opcode: int) -> tuple[int, int]:
    """(base cycles, adjustment: fixed=0, absX=1, absY=2, indY=3, branch=4)."""
    if type(opcode) is not int or opcode not in OPS:
        raise ValueError('Require an original documented NMOS 6502 opcode')
    name, mode, _ = OPS[opcode]
    if name in SPECIAL:
        return SPECIAL[name], 0
    if name == 'JMP':
        return (5 if mode == 'ind' else 3), 0
    if name in BRANCHES:
        return 2, 4
    if mode in ('imp', 'acc'):
        return 2, 0
    if name in RMW:
        return {'zp': 5, 'zpx': 6, 'abs': 6, 'absx': 7}[mode], 0
    if name in ('STA', 'STX', 'STY'):
        return {'zp': 3, 'zpx': 4, 'zpy': 4, 'abs': 4,
                'absx': 5, 'absy': 5, 'ix': 6, 'iy': 6}[mode], 0
    return READ[mode], {'absx': 1, 'absy': 2, 'iy': 3}.get(mode, 0)


def integer(value: int, maximum: int, label: str) -> None:
    if type(value) is not int or not 0 <= value <= maximum:
        raise ValueError(f'{label} must be an integer in 0..{maximum}')


@dataclass(frozen=True)
class Instruction:
    opcode: int
    pc: int
    operand: int = 0
    p: int = 0
    x: int = 0
    y: int = 0
    pointer: int | None = None

    def cost(self) -> int:
        base, adjustment = metadata(self.opcode)
        for name in ('pc', 'operand'):
            integer(getattr(self, name), 65535, name)
        for name in ('p', 'x', 'y'):
            integer(getattr(self, name), 255, name)
        if self.pointer is not None:
            integer(self.pointer, 65535, 'pointer')
        if OPS[self.opcode][2] == 2 and self.operand > 255:
            raise ValueError('Two-byte instruction requires an eight-bit operand')
        if adjustment == 4:
            mask, sense = BRANCHES[OPS[self.opcode][0]]
            if bool(self.p & mask) != sense:
                return base
            following = (self.pc + 2) & 65535
            displacement = self.operand if self.operand < 128 else self.operand - 256
            target = (following + displacement) & 65535
            return base + 1 + int((following ^ target) & 0xFF00 != 0)
        if adjustment:
            if adjustment == 3 and self.pointer is None:
                raise ValueError('Indirect-Y reads require a pre-instruction pointer snapshot')
            address = self.pointer if adjustment == 3 else self.operand
            index = self.x if adjustment == 1 else self.y
            return base + int((address & 255) + index > 255)
        return base

    def record(self) -> bytes:
        self.cost()
        return bytes((self.opcode, self.p, self.x, self.y)) + self.operand.to_bytes(2, 'little') + self.pc.to_bytes(2, 'little') + (self.pointer or 0).to_bytes(2, 'little') + bytes((self.pointer is not None, 0, 0, 0))


def tables() -> str:
    """Tables for the isolated native accountant; the emulator is the oracle."""
    out = ['; Generated by guest_cycles.py; zero means unsupported, never zero-cost.']
    for label, index in [('GuestCycleBase', 0), ('GuestCycleAdjust', 1)]:
        values = [metadata(op)[index] if op in OPS else 0 for op in range(256)]
        out.append(label+':')
        out.extend('    .byte '+','.join(str(v) for v in values[i:i+16]) for i in range(0, 256, 16))
    return '\n'.join(out)+'\n'


def account_window(records: list[dict], interrupt_entries: dict[int, str]) -> dict:
    """Check a complete authored cartridge-only observation window.

    This does NOT choose when to deliver an interrupt. The caller supplies known
    handler entry PCs; observed seven-cycle gaps are accounted separately. Any
    other gap, changed instruction duration, missing/overlapping record, or
    unsupported opcode rejects the window. First/last partial-frame time is not
    extrapolated. Data from a selectively sampled trace is not a complete window.
    """
    if not isinstance(records, list) or not records:
        raise ValueError('Require a nonempty complete instruction window')
    if not isinstance(interrupt_entries, dict) or any(type(pc) is not int or not 0x8000 <= pc <= 0xFFFD or kind not in ('nmi', 'irq') for pc,kind in interrupt_entries.items()):
        raise ValueError('Explicit interrupt entry addresses and types required')
    required={'start','end','pc','operand','pointer','next_pc','opcode','p','x','y','a','s','valid','reserved'}
    previous=None;execution=0;interrupt_cycles=0;interrupts=[]
    for index,row in enumerate(records):
        if not isinstance(row,dict) or set(row)!=required or row['valid']!=1 or type(row['valid']) is not int or row['reserved']!=0 or type(row['reserved']) is not int:
            raise ValueError('Invalid full instruction record')
        for key in ('start','end'):
            integer(row[key],2**64-1,key)
        for key in ('pc','operand','pointer','next_pc'):
            integer(row[key],65535,key)
        if not 0x8000 <= row['pc'] <= 0xFFFD:
            raise ValueError('Window is not a supported cartridge-only capture')
        for key in ('opcode','p','x','y','a','s'):
            integer(row[key],255,key)
        size=OPS.get(row['opcode'],('', '', 0))[2]
        operand=row['operand'] if size==3 else row['operand']&255 if size==2 else 0
        cost=Instruction(row['opcode'],row['pc'],operand,row['p'],row['x'],row['y'],row['pointer']).cost()
        if row['end']-row['start'] != cost:
            raise ValueError('Instruction duration includes unexplained timing or a model mismatch')
        if previous is not None:
            gap=row['start']-previous['end']
            if gap:
                if gap != 7 or row['pc'] not in interrupt_entries:
                    raise ValueError('Unexplained inter-instruction gap; no budget can be certified')
                interrupts.append({'before_record':index,'kind':interrupt_entries[row['pc']],'cycles':7})
                interrupt_cycles+=7
            elif previous['next_pc']!=row['pc']:
                raise ValueError('Instruction sequence discontinuity')
        execution+=cost;previous=row
    span=records[-1]['end']-records[0]['start']
    if execution+interrupt_cycles!=span:
        raise ValueError('Cycle accounting does not close')
    return {'passed':True,'instructions':len(records),'instruction_cycles':execution,
            'interrupt_cycles':interrupt_cycles,'interrupts':interrupts,'span_cycles':span,
            'unexplained_cycles':0,'first_timestamp':records[0]['start'],
            'last_timestamp':records[-1]['end'],'interrupt_delivery_predicted':False,
            'scope':'Complete supplied cartridge-only window; handler entries observed, not scheduled. No DMA/DMC stall inference or full-frame extrapolation.'}
